version: '2.3'

services:
  tf_gpu:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    runtime: ${runtime}
    ports:
      - "${external_port}:8888"
    networks:
      - default
      - web
    volumes:
      - ./notebooks:/code/notebooks
networks:
  web:
    external:
      name: nginx-server_web
